# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/bionic64"

  config.vm.provider "virtualbox" do |vb|
    vb.memory = 3048
    vb.cpus = 2
    vb.customize [ "modifyvm", :id, "--uartmode1", "disconnected" ]
  end

  config.vm.network "forwarded_port", guest: 51075, host: 51075
  config.vm.network "forwarded_port", guest: 51076, host: 51076

  config.vm.synced_folder "../", "/vagrant"

  config.ssh.forward_agent=true

  config.vm.provision "shell", inline: <<-SHELL
#    apt-get update
#    curl -sL https://deb.nodesource.com/setup_10.x | sudo -E bash -
    curl -sL https://deb.nodesource.com/setup_10.x | sudo bash -
    curl -sS https://dl.yarnpkg.com/debian/pubkey.gpg | sudo apt-key add -
    echo "deb https://dl.yarnpkg.com/debian/ stable main" | sudo tee /etc/apt/sources.list.d/yarn.list
    sudo apt update
    sudo apt install -y nodejs
    sudo apt install -y yarn
#    sudo apt install -y python-minimal
#    sudo apt install -y build-essential
    npm install --global lerna
    npm install -g quasar-cli
#    yarn global add quasar-cli
    rsync -avzh /vagrant/ /_vagrant/
    cd /_vagrant/app
    yarn config set workspaces-experimental true
#    yarn
    lerna bootstrap
  SHELL

  config.vm.provider :virtualbox do |vm|
    vm.customize ["setextradata", :id, "VBoxInternal2/SharedFoldersEnableSymlinksCreate/vagrant", "1"]
  end
end
